# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/authorization.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)dgt_settings/protobuf/authorization.proto\"6\n\x11\x43onnectionRequest\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x0f\n\x07network\x18\x02 \x01(\t\"\xca\x02\n\x12\x43onnectionResponse\x12,\n\x05roles\x18\x01 \x03(\x0b\x32\x1d.ConnectionResponse.RoleEntry\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.ConnectionResponse.Status\x1a^\n\tRoleEntry\x12\x17\n\x04role\x18\x01 \x01(\x0e\x32\t.RoleType\x12\x38\n\tauth_type\x18\x02 \x01(\x0e\x32%.ConnectionResponse.AuthorizationType\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"K\n\x11\x41uthorizationType\x12\x1c\n\x18\x41UTHORIZATION_TYPE_UNSET\x10\x00\x12\t\n\x05TRUST\x10\x01\x12\r\n\tCHALLENGE\x10\x02\"I\n\x19\x41uthorizationTrustRequest\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType\x12\x12\n\npublic_key\x18\x02 \x01(\t\"6\n\x1a\x41uthorizationTrustResponse\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType\"6\n\x16\x41uthorizationViolation\x12\x1c\n\tviolation\x18\x01 \x01(\x0e\x32\t.RoleType\"\x1f\n\x1d\x41uthorizationChallengeRequest\"1\n\x1e\x41uthorizationChallengeResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"_\n\x1c\x41uthorizationChallengeSubmit\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x18\n\x05roles\x18\x04 \x03(\x0e\x32\t.RoleType\"8\n\x1c\x41uthorizationChallengeResult\x12\x18\n\x05roles\x18\x01 \x03(\x0e\x32\t.RoleType*5\n\x08RoleType\x12\x13\n\x0fROLE_TYPE_UNSET\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x12\x0b\n\x07NETWORK\x10\x02\x42,\n\x15sawtooth.sdk.protobufP\x01Z\x11\x61uthorization_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.authorization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\021authorization_pb2'
  _globals['_ROLETYPE']._serialized_start=860
  _globals['_ROLETYPE']._serialized_end=913
  _globals['_CONNECTIONREQUEST']._serialized_start=45
  _globals['_CONNECTIONREQUEST']._serialized_end=99
  _globals['_CONNECTIONRESPONSE']._serialized_start=102
  _globals['_CONNECTIONRESPONSE']._serialized_end=432
  _globals['_CONNECTIONRESPONSE_ROLEENTRY']._serialized_start=214
  _globals['_CONNECTIONRESPONSE_ROLEENTRY']._serialized_end=308
  _globals['_CONNECTIONRESPONSE_STATUS']._serialized_start=310
  _globals['_CONNECTIONRESPONSE_STATUS']._serialized_end=355
  _globals['_CONNECTIONRESPONSE_AUTHORIZATIONTYPE']._serialized_start=357
  _globals['_CONNECTIONRESPONSE_AUTHORIZATIONTYPE']._serialized_end=432
  _globals['_AUTHORIZATIONTRUSTREQUEST']._serialized_start=434
  _globals['_AUTHORIZATIONTRUSTREQUEST']._serialized_end=507
  _globals['_AUTHORIZATIONTRUSTRESPONSE']._serialized_start=509
  _globals['_AUTHORIZATIONTRUSTRESPONSE']._serialized_end=563
  _globals['_AUTHORIZATIONVIOLATION']._serialized_start=565
  _globals['_AUTHORIZATIONVIOLATION']._serialized_end=619
  _globals['_AUTHORIZATIONCHALLENGEREQUEST']._serialized_start=621
  _globals['_AUTHORIZATIONCHALLENGEREQUEST']._serialized_end=652
  _globals['_AUTHORIZATIONCHALLENGERESPONSE']._serialized_start=654
  _globals['_AUTHORIZATIONCHALLENGERESPONSE']._serialized_end=703
  _globals['_AUTHORIZATIONCHALLENGESUBMIT']._serialized_start=705
  _globals['_AUTHORIZATIONCHALLENGESUBMIT']._serialized_end=800
  _globals['_AUTHORIZATIONCHALLENGERESULT']._serialized_start=802
  _globals['_AUTHORIZATIONCHALLENGERESULT']._serialized_end=858
# @@protoc_insertion_point(module_scope)
