# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/batch.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import transaction_pb2 as dgt__settings_dot_protobuf_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!dgt_settings/protobuf/batch.proto\x1a\'dgt_settings/protobuf/transaction.proto\"A\n\x0b\x42\x61tchHeader\x12\x19\n\x11signer_public_key\x18\x01 \x01(\t\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\t\"w\n\x05\x42\x61tch\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x18\n\x10header_signature\x18\x02 \x01(\t\x12\"\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x0c.Transaction\x12\r\n\x05trace\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\r\"M\n\tBatchList\x12\x17\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x06.Batch\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x0c\x12\x11\n\tblock_num\x18\x03 \x01(\rB$\n\x15sawtooth.sdk.protobufP\x01Z\tbatch_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.batch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\tbatch_pb2'
  _globals['_BATCHHEADER']._serialized_start=78
  _globals['_BATCHHEADER']._serialized_end=143
  _globals['_BATCH']._serialized_start=145
  _globals['_BATCH']._serialized_end=264
  _globals['_BATCHLIST']._serialized_start=266
  _globals['_BATCHLIST']._serialized_end=343
# @@protoc_insertion_point(module_scope)
