# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/bgx_validator_registry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2dgt_settings/protobuf/bgx_validator_registry.proto\"w\n\x10\x42gxValidatorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04node\x18\x03 \x01(\t\x12#\n\x0bsignup_info\x18\x04 \x01(\x0b\x32\x0e.BgxSignUpInfo\x12\x16\n\x0etransaction_id\x18\x05 \x01(\t\"N\n\rBgxSignUpInfo\x12\x17\n\x0fpbft_public_key\x18\x01 \x01(\t\x12\x15\n\ranti_sybil_id\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"_\n\x0f\x42gxValidatorMap\x12\'\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x16.BgxValidatorMap.Entry\x1a#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"x\n\x1b\x42gxValidatorRegistryPayload\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04node\x18\x04 \x01(\t\x12#\n\x0bsignup_info\x18\x05 \x01(\x0b\x32\x0e.BgxSignUpInfoB\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.bgx_validator_registry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030sawtooth.config.protobufP\001'
  _globals['_BGXVALIDATORINFO']._serialized_start=54
  _globals['_BGXVALIDATORINFO']._serialized_end=173
  _globals['_BGXSIGNUPINFO']._serialized_start=175
  _globals['_BGXSIGNUPINFO']._serialized_end=253
  _globals['_BGXVALIDATORMAP']._serialized_start=255
  _globals['_BGXVALIDATORMAP']._serialized_end=350
  _globals['_BGXVALIDATORMAP_ENTRY']._serialized_start=315
  _globals['_BGXVALIDATORMAP_ENTRY']._serialized_end=350
  _globals['_BGXVALIDATORREGISTRYPAYLOAD']._serialized_start=352
  _globals['_BGXVALIDATORREGISTRYPAYLOAD']._serialized_end=472
# @@protoc_insertion_point(module_scope)
