# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/block.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import batch_pb2 as dgt__settings_dot_protobuf_dot_batch__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!dgt_settings/protobuf/block.proto\x1a!dgt_settings/protobuf/batch.proto\"\x95\x01\n\x0b\x42lockHeader\x12\x11\n\tblock_num\x18\x01 \x01(\x04\x12\x19\n\x11previous_block_id\x18\x02 \x01(\t\x12\x19\n\x11signer_public_key\x18\x03 \x01(\t\x12\x11\n\tbatch_ids\x18\x04 \x03(\t\x12\x11\n\tconsensus\x18\x05 \x01(\x0c\x12\x17\n\x0fstate_root_hash\x18\x06 \x01(\t\"J\n\x05\x42lock\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x18\n\x10header_signature\x18\x02 \x01(\t\x12\x17\n\x07\x62\x61tches\x18\x03 \x03(\x0b\x32\x06.BatchB$\n\x15sawtooth.sdk.protobufP\x01Z\tblock_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.block_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\tblock_pb2'
  _globals['_BLOCKHEADER']._serialized_start=73
  _globals['_BLOCKHEADER']._serialized_end=222
  _globals['_BLOCK']._serialized_start=224
  _globals['_BLOCK']._serialized_end=298
# @@protoc_insertion_point(module_scope)
