# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_heads.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dgt_settings/protobuf/client_heads.proto\"(\n\x15\x43lientHeadsGetRequest\x12\x0f\n\x07head_id\x18\x01 \x01(\t\"\x86\x01\n\x16\x43lientHeadsGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientHeadsGetResponse.Status\x12\r\n\x05heads\x18\x02 \x03(\t\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"$\n\x12\x44\x61gGraphGetRequest\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\"\x80\x01\n\x13\x44\x61gGraphGetResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.DagGraphGetResponse.Status\x12\r\n\x05graph\x18\x02 \x01(\t\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42&\n\x15sawtooth.sdk.protobufP\x01Z\x0b\x63lient_headb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_heads_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\013client_head'
  _globals['_CLIENTHEADSGETREQUEST']._serialized_start=44
  _globals['_CLIENTHEADSGETREQUEST']._serialized_end=84
  _globals['_CLIENTHEADSGETRESPONSE']._serialized_start=87
  _globals['_CLIENTHEADSGETRESPONSE']._serialized_end=221
  _globals['_CLIENTHEADSGETRESPONSE_STATUS']._serialized_start=176
  _globals['_CLIENTHEADSGETRESPONSE_STATUS']._serialized_end=221
  _globals['_DAGGRAPHGETREQUEST']._serialized_start=223
  _globals['_DAGGRAPHGETREQUEST']._serialized_end=259
  _globals['_DAGGRAPHGETRESPONSE']._serialized_start=262
  _globals['_DAGGRAPHGETRESPONSE']._serialized_end=390
  _globals['_DAGGRAPHGETRESPONSE_STATUS']._serialized_start=176
  _globals['_DAGGRAPHGETRESPONSE_STATUS']._serialized_end=221
# @@protoc_insertion_point(module_scope)
