# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_state.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import client_list_control_pb2 as dgt__settings_dot_protobuf_dot_client__list__control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dgt_settings/protobuf/client_state.proto\x1a/dgt_settings/protobuf/client_list_control.proto\"\x8a\x01\n\x16\x43lientStateListRequest\x12\x12\n\nstate_root\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingControls\x12$\n\x07sorting\x18\x05 \x03(\x0b\x32\x13.ClientSortControls\"\x91\x03\n\x17\x43lientStateListResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientStateListResponse.Status\x12/\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x1e.ClientStateListResponse.Entry\x12\x12\n\nstate_root\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingResponse\x1a&\n\x05\x45ntry\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xb0\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x12\n\x0eINVALID_PAGING\x10\x06\x12\x10\n\x0cINVALID_SORT\x10\x07\x12\x13\n\x0fINVALID_ADDRESS\x10\x08\x12\x10\n\x0cINVALID_ROOT\x10\t\"<\n\x15\x43lientStateGetRequest\x12\x12\n\nstate_root\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"\xf8\x01\n\x16\x43lientStateGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientStateGetResponse.Status\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x12\n\nstate_root\x18\x03 \x01(\t\"\x8a\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x13\n\x0fINVALID_ADDRESS\x10\x06\x12\x10\n\x0cINVALID_ROOT\x10\x07\x42+\n\x15sawtooth.sdk.protobufP\x01Z\x10\x63lient_state_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\020client_state_pb2'
  _globals['_CLIENTSTATELISTREQUEST']._serialized_start=94
  _globals['_CLIENTSTATELISTREQUEST']._serialized_end=232
  _globals['_CLIENTSTATELISTRESPONSE']._serialized_start=235
  _globals['_CLIENTSTATELISTRESPONSE']._serialized_end=636
  _globals['_CLIENTSTATELISTRESPONSE_ENTRY']._serialized_start=419
  _globals['_CLIENTSTATELISTRESPONSE_ENTRY']._serialized_end=457
  _globals['_CLIENTSTATELISTRESPONSE_STATUS']._serialized_start=460
  _globals['_CLIENTSTATELISTRESPONSE_STATUS']._serialized_end=636
  _globals['_CLIENTSTATEGETREQUEST']._serialized_start=638
  _globals['_CLIENTSTATEGETREQUEST']._serialized_end=698
  _globals['_CLIENTSTATEGETRESPONSE']._serialized_start=701
  _globals['_CLIENTSTATEGETRESPONSE']._serialized_end=949
  _globals['_CLIENTSTATEGETRESPONSE_STATUS']._serialized_start=811
  _globals['_CLIENTSTATEGETRESPONSE_STATUS']._serialized_end=949
# @@protoc_insertion_point(module_scope)
