# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_event.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import events_pb2 as dgt__settings_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dgt_settings/protobuf/client_event.proto\x1a\"dgt_settings/protobuf/events.proto\"g\n\x1c\x43lientEventsSubscribeRequest\x12)\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x12.EventSubscription\x12\x1c\n\x14last_known_block_ids\x18\x02 \x03(\t\"\xbb\x01\n\x1d\x43lientEventsSubscribeResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.ClientEventsSubscribeResponse.Status\x12\x18\n\x10response_message\x18\x02 \x01(\t\"I\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINVALID_FILTER\x10\x02\x12\x11\n\rUNKNOWN_BLOCK\x10\x03\" \n\x1e\x43lientEventsUnsubscribeRequest\"\x92\x01\n\x1f\x43lientEventsUnsubscribeResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.ClientEventsUnsubscribeResponse.Status\"6\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\"V\n\x16\x43lientEventsGetRequest\x12)\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x12.EventSubscription\x12\x11\n\tblock_ids\x18\x02 \x03(\t\"\xc1\x01\n\x17\x43lientEventsGetResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.ClientEventsGetResponse.Status\x12\x16\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x06.Event\"]\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x12\n\x0eINVALID_FILTER\x10\x03\x12\x11\n\rUNKNOWN_BLOCK\x10\x04\x42+\n\x15sawtooth.sdk.protobufP\x01Z\x10\x63lient_event_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\020client_event_pb2'
  _globals['_CLIENTEVENTSSUBSCRIBEREQUEST']._serialized_start=80
  _globals['_CLIENTEVENTSSUBSCRIBEREQUEST']._serialized_end=183
  _globals['_CLIENTEVENTSSUBSCRIBERESPONSE']._serialized_start=186
  _globals['_CLIENTEVENTSSUBSCRIBERESPONSE']._serialized_end=373
  _globals['_CLIENTEVENTSSUBSCRIBERESPONSE_STATUS']._serialized_start=300
  _globals['_CLIENTEVENTSSUBSCRIBERESPONSE_STATUS']._serialized_end=373
  _globals['_CLIENTEVENTSUNSUBSCRIBEREQUEST']._serialized_start=375
  _globals['_CLIENTEVENTSUNSUBSCRIBEREQUEST']._serialized_end=407
  _globals['_CLIENTEVENTSUNSUBSCRIBERESPONSE']._serialized_start=410
  _globals['_CLIENTEVENTSUNSUBSCRIBERESPONSE']._serialized_end=556
  _globals['_CLIENTEVENTSUNSUBSCRIBERESPONSE_STATUS']._serialized_start=502
  _globals['_CLIENTEVENTSUNSUBSCRIBERESPONSE_STATUS']._serialized_end=556
  _globals['_CLIENTEVENTSGETREQUEST']._serialized_start=558
  _globals['_CLIENTEVENTSGETREQUEST']._serialized_end=644
  _globals['_CLIENTEVENTSGETRESPONSE']._serialized_start=647
  _globals['_CLIENTEVENTSGETRESPONSE']._serialized_end=840
  _globals['_CLIENTEVENTSGETRESPONSE_STATUS']._serialized_start=747
  _globals['_CLIENTEVENTSGETRESPONSE_STATUS']._serialized_end=840
# @@protoc_insertion_point(module_scope)
