# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_topology.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+dgt_settings/protobuf/client_topology.proto\"\x1a\n\x18\x43lientTopologyGetRequest\"\x8f\x01\n\x19\x43lientTopologyGetResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.ClientTopologyGetResponse.Status\x12\x10\n\x08topology\x18\x02 \x01(\x0c\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x16\n\x14\x43lientGateGetRequest\"\x84\x01\n\x15\x43lientGateGetResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.ClientGateGetResponse.Status\x12\r\n\x05gates\x18\x02 \x01(\x0c\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42*\n\x15sawtooth.sdk.protobufP\x01Z\x0f\x63lient_topologyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_topology_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\017client_topology'
  _globals['_CLIENTTOPOLOGYGETREQUEST']._serialized_start=47
  _globals['_CLIENTTOPOLOGYGETREQUEST']._serialized_end=73
  _globals['_CLIENTTOPOLOGYGETRESPONSE']._serialized_start=76
  _globals['_CLIENTTOPOLOGYGETRESPONSE']._serialized_end=219
  _globals['_CLIENTTOPOLOGYGETRESPONSE_STATUS']._serialized_start=174
  _globals['_CLIENTTOPOLOGYGETRESPONSE_STATUS']._serialized_end=219
  _globals['_CLIENTGATEGETREQUEST']._serialized_start=221
  _globals['_CLIENTGATEGETREQUEST']._serialized_end=243
  _globals['_CLIENTGATEGETRESPONSE']._serialized_start=246
  _globals['_CLIENTGATEGETRESPONSE']._serialized_end=378
  _globals['_CLIENTGATEGETRESPONSE_STATUS']._serialized_start=174
  _globals['_CLIENTGATEGETRESPONSE_STATUS']._serialized_end=219
# @@protoc_insertion_point(module_scope)
