# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_list_control.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/dgt_settings/protobuf/client_list_control.proto\"4\n\x14\x43lientPagingControls\x12\r\n\x05start\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"B\n\x14\x43lientPagingResponse\x12\x0c\n\x04next\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"3\n\x12\x43lientSortControls\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x0f\n\x07reverse\x18\x02 \x01(\x08\x42\x32\n\x15sawtooth.sdk.protobufP\x01Z\x17\x63lient_list_control_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_list_control_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\027client_list_control_pb2'
  _globals['_CLIENTPAGINGCONTROLS']._serialized_start=51
  _globals['_CLIENTPAGINGCONTROLS']._serialized_end=103
  _globals['_CLIENTPAGINGRESPONSE']._serialized_start=105
  _globals['_CLIENTPAGINGRESPONSE']._serialized_end=171
  _globals['_CLIENTSORTCONTROLS']._serialized_start=173
  _globals['_CLIENTSORTCONTROLS']._serialized_end=224
# @@protoc_insertion_point(module_scope)
