# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_transaction.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import transaction_pb2 as dgt__settings_dot_protobuf_dot_transaction__pb2
from dgt_settings.protobuf import client_list_control_pb2 as dgt__settings_dot_protobuf_dot_client__list__control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.dgt_settings/protobuf/client_transaction.proto\x1a\'dgt_settings/protobuf/transaction.proto\x1a/dgt_settings/protobuf/client_list_control.proto\"\x95\x01\n\x1c\x43lientTransactionListRequest\x12\x0f\n\x07head_id\x18\x01 \x01(\t\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\t\x12%\n\x06paging\x18\x03 \x01(\x0b\x32\x15.ClientPagingControls\x12$\n\x07sorting\x18\x04 \x03(\x0b\x32\x13.ClientSortControls\"\xce\x02\n\x1d\x43lientTransactionListResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.ClientTransactionListResponse.Status\x12\"\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x0c.Transaction\x12\x0f\n\x07head_id\x18\x03 \x01(\t\x12%\n\x06paging\x18\x04 \x01(\x0b\x32\x15.ClientPagingResponse\"\x99\x01\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\r\n\tNOT_READY\x10\x03\x12\x0b\n\x07NO_ROOT\x10\x04\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x12\n\x0eINVALID_PAGING\x10\x06\x12\x10\n\x0cINVALID_SORT\x10\x07\x12\x0e\n\nINVALID_ID\x10\x08\"5\n\x1b\x43lientTransactionGetRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\xd0\x01\n\x1c\x43lientTransactionGetResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.ClientTransactionGetResponse.Status\x12!\n\x0btransaction\x18\x02 \x01(\x0b\x32\x0c.Transaction\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42\x31\n\x15sawtooth.sdk.protobufP\x01Z\x16\x63lient_transaction_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\026client_transaction_pb2'
  _globals['_CLIENTTRANSACTIONLISTREQUEST']._serialized_start=141
  _globals['_CLIENTTRANSACTIONLISTREQUEST']._serialized_end=290
  _globals['_CLIENTTRANSACTIONLISTRESPONSE']._serialized_start=293
  _globals['_CLIENTTRANSACTIONLISTRESPONSE']._serialized_end=627
  _globals['_CLIENTTRANSACTIONLISTRESPONSE_STATUS']._serialized_start=474
  _globals['_CLIENTTRANSACTIONLISTRESPONSE_STATUS']._serialized_end=627
  _globals['_CLIENTTRANSACTIONGETREQUEST']._serialized_start=629
  _globals['_CLIENTTRANSACTIONGETREQUEST']._serialized_end=682
  _globals['_CLIENTTRANSACTIONGETRESPONSE']._serialized_start=685
  _globals['_CLIENTTRANSACTIONGETRESPONSE']._serialized_end=893
  _globals['_CLIENTTRANSACTIONGETRESPONSE_STATUS']._serialized_start=806
  _globals['_CLIENTTRANSACTIONGETRESPONSE_STATUS']._serialized_end=893
# @@protoc_insertion_point(module_scope)
