# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_peers.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dgt_settings/protobuf/client_peers.proto\"\x87\x01\n\x15\x43lientPeersGetRequest\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.ClientPeersGetRequest.Status\"?\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\r\n\tMALICIOUS\x10\x01\x12\x0e\n\nMALICIOUS1\x10\x02\x12\x0e\n\nMALICIOUS2\x10\x03\"\x86\x01\n\x16\x43lientPeersGetResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.ClientPeersGetResponse.Status\x12\r\n\x05peers\x18\x02 \x03(\t\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x8f\x01\n\x19\x43lientPeersControlRequest\x12.\n\x04mode\x18\x01 \x01(\x0e\x32 .ClientPeersControlRequest.Modes\x12\x0f\n\x07\x63luster\x18\x02 \x01(\t\x12\x0c\n\x04peer\x18\x03 \x01(\t\"#\n\x05Modes\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04INFO\x10\x02\"{\n\x1a\x43lientPeersControlResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".ClientPeersControlResponse.Status\x12\x0c\n\x04info\x18\x02 \x01(\t\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42&\n\x15sawtooth.sdk.protobufP\x01Z\x0b\x63lient_peerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_peers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\013client_peer'
  _globals['_CLIENTPEERSGETREQUEST']._serialized_start=45
  _globals['_CLIENTPEERSGETREQUEST']._serialized_end=180
  _globals['_CLIENTPEERSGETREQUEST_STATUS']._serialized_start=117
  _globals['_CLIENTPEERSGETREQUEST_STATUS']._serialized_end=180
  _globals['_CLIENTPEERSGETRESPONSE']._serialized_start=183
  _globals['_CLIENTPEERSGETRESPONSE']._serialized_end=317
  _globals['_CLIENTPEERSGETRESPONSE_STATUS']._serialized_start=272
  _globals['_CLIENTPEERSGETRESPONSE_STATUS']._serialized_end=317
  _globals['_CLIENTPEERSCONTROLREQUEST']._serialized_start=320
  _globals['_CLIENTPEERSCONTROLREQUEST']._serialized_end=463
  _globals['_CLIENTPEERSCONTROLREQUEST_MODES']._serialized_start=428
  _globals['_CLIENTPEERSCONTROLREQUEST_MODES']._serialized_end=463
  _globals['_CLIENTPEERSCONTROLRESPONSE']._serialized_start=465
  _globals['_CLIENTPEERSCONTROLRESPONSE']._serialized_end=588
  _globals['_CLIENTPEERSCONTROLRESPONSE_STATUS']._serialized_start=561
  _globals['_CLIENTPEERSCONTROLRESPONSE_STATUS']._serialized_end=588
# @@protoc_insertion_point(module_scope)
