# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/client_receipt.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import transaction_receipt_pb2 as dgt__settings_dot_protobuf_dot_transaction__receipt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dgt_settings/protobuf/client_receipt.proto\x1a/dgt_settings/protobuf/transaction_receipt.proto\"\x87\x01\n\x17\x43lientReceiptGetRequest\x12+\n\x03ind\x18\x01 \x01(\x0e\x32\x1e.ClientReceiptGetRequest.Index\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\t\"&\n\x05Index\x12\r\n\tINDEX_TNX\x10\x00\x12\x0e\n\nINDEX_ADDR\x10\x01\"\xcc\x01\n\x18\x43lientReceiptGetResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ClientReceiptGetResponse.Status\x12%\n\x08receipts\x18\x02 \x03(\x0b\x32\x13.TransactionReceipt\"W\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x0f\n\x0bNO_RESOURCE\x10\x05\x12\x0e\n\nINVALID_ID\x10\x08\x42-\n\x15sawtooth.sdk.protobufP\x01Z\x12\x63lient_receipt_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.client_receipt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\022client_receipt_pb2'
  _globals['_CLIENTRECEIPTGETREQUEST']._serialized_start=96
  _globals['_CLIENTRECEIPTGETREQUEST']._serialized_end=231
  _globals['_CLIENTRECEIPTGETREQUEST_INDEX']._serialized_start=193
  _globals['_CLIENTRECEIPTGETREQUEST_INDEX']._serialized_end=231
  _globals['_CLIENTRECEIPTGETRESPONSE']._serialized_start=234
  _globals['_CLIENTRECEIPTGETRESPONSE']._serialized_end=438
  _globals['_CLIENTRECEIPTGETRESPONSE_STATUS']._serialized_start=351
  _globals['_CLIENTRECEIPTGETRESPONSE_STATUS']._serialized_end=438
# @@protoc_insertion_point(module_scope)
