# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/identity.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$dgt_settings/protobuf/identity.proto\"\xae\x01\n\x06Policy\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\r.Policy.Entry\x1a\x35\n\x05\x45ntry\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.Policy.EntryType\x12\x0b\n\x03key\x18\x02 \x01(\t\"?\n\tEntryType\x12\x14\n\x10\x45NTRY_TYPE_UNSET\x10\x00\x12\x0e\n\nPERMIT_KEY\x10\x01\x12\x0c\n\x08\x44\x45NY_KEY\x10\x02\"\'\n\nPolicyList\x12\x19\n\x08policies\x18\x01 \x03(\x0b\x32\x07.Policy\")\n\x04Role\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bpolicy_name\x18\x02 \x01(\t\" \n\x08RoleList\x12\x14\n\x05roles\x18\x01 \x03(\x0b\x32\x05.RoleB\x1e\n\x1asawtooth.identity.protobufP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.identity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032sawtooth.identity.protobufP\001'
  _globals['_POLICY']._serialized_start=41
  _globals['_POLICY']._serialized_end=215
  _globals['_POLICY_ENTRY']._serialized_start=97
  _globals['_POLICY_ENTRY']._serialized_end=150
  _globals['_POLICY_ENTRYTYPE']._serialized_start=152
  _globals['_POLICY_ENTRYTYPE']._serialized_end=215
  _globals['_POLICYLIST']._serialized_start=217
  _globals['_POLICYLIST']._serialized_end=256
  _globals['_ROLE']._serialized_start=258
  _globals['_ROLE']._serialized_end=299
  _globals['_ROLELIST']._serialized_start=301
  _globals['_ROLELIST']._serialized_end=333
# @@protoc_insertion_point(module_scope)
