# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/merkle.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"dgt_settings/protobuf/merkle.proto\"\x95\x01\n\x0e\x43hangeLogEntry\x12\x0e\n\x06parent\x18\x01 \x01(\x0c\x12\x11\n\tadditions\x18\x02 \x03(\x0c\x12-\n\nsuccessors\x18\x03 \x03(\x0b\x32\x19.ChangeLogEntry.Successor\x1a\x31\n\tSuccessor\x12\x11\n\tsuccessor\x18\x01 \x01(\x0c\x12\x11\n\tdeletions\x18\x02 \x03(\x0c\x42%\n\x15sawtooth.sdk.protobufP\x01Z\nmerkle_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.merkle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\nmerkle_pb2'
  _globals['_CHANGELOGENTRY']._serialized_start=39
  _globals['_CHANGELOGENTRY']._serialized_end=188
  _globals['_CHANGELOGENTRY_SUCCESSOR']._serialized_start=139
  _globals['_CHANGELOGENTRY_SUCCESSOR']._serialized_end=188
# @@protoc_insertion_point(module_scope)
