# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/pbft_consensus.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import consensus_pb2 as dgt__settings_dot_protobuf_dot_consensus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dgt_settings/protobuf/pbft_consensus.proto\x1a%dgt_settings/protobuf/consensus.proto\"[\n\x10PbftBlockMessage\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x0c\x12\x11\n\tsigner_id\x18\x03 \x01(\x0c\x12\x11\n\tblock_num\x18\x04 \x01(\x04\x12\x0f\n\x07summary\x18\x06 \x01(\x0c\"\x98\x02\n\x0fPbftMessageInfo\x12\x32\n\x08msg_type\x18\x01 \x01(\x0e\x32 .PbftMessageInfo.PbftMessageType\x12\x0c\n\x04view\x18\x02 \x01(\x04\x12\x0f\n\x07seq_num\x18\x03 \x01(\x04\x12\x11\n\tsigner_id\x18\x04 \x01(\x0c\"\x9e\x01\n\x0fPbftMessageType\x12\x13\n\x0fPRE_PREPARE_MSG\x10\x00\x12\x0f\n\x0bPREPARE_MSG\x10\x01\x12\x0e\n\nCOMMIT_MSG\x10\x02\x12\x12\n\x0e\x43HECKPOINT_MSG\x10\x03\x12\x12\n\x0eVIEWCHANGE_MSG\x10\x04\x12\x13\n\x0f\x41RBITRATION_MSG\x10\x05\x12\x18\n\x14\x41RBITRATION_DONE_MSG\x10\x06\">\n\x0bPbftMessage\x12\x1e\n\x04info\x18\x01 \x01(\x0b\x32\x10.PbftMessageInfo\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"0\n\x0ePbftViewChange\x12\x1e\n\x04info\x18\x01 \x01(\x0b\x32\x10.PbftMessageInfo\"=\n\x0bPbftNewView\x12.\n\x0cview_changes\x18\x01 \x03(\x0b\x32\x18.ConsensusPeerMessageNew\"W\n\x0ePbftSignedVote\x12\x14\n\x0cheader_bytes\x18\x01 \x01(\x0c\x12\x18\n\x10header_signature\x18\x02 \x01(\x0c\x12\x15\n\rmessage_bytes\x18\x03 \x01(\x0c\"\\\n\x08PbftSeal\x12 \n\x05\x62lock\x18\x01 \x01(\x0b\x32\x11.PbftBlockMessage\x12.\n\x0c\x63ommit_votes\x18\x02 \x03(\x0b\x32\x18.ConsensusPeerMessageNewb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.pbft_consensus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBFTBLOCKMESSAGE']._serialized_start=85
  _globals['_PBFTBLOCKMESSAGE']._serialized_end=176
  _globals['_PBFTMESSAGEINFO']._serialized_start=179
  _globals['_PBFTMESSAGEINFO']._serialized_end=459
  _globals['_PBFTMESSAGEINFO_PBFTMESSAGETYPE']._serialized_start=301
  _globals['_PBFTMESSAGEINFO_PBFTMESSAGETYPE']._serialized_end=459
  _globals['_PBFTMESSAGE']._serialized_start=461
  _globals['_PBFTMESSAGE']._serialized_end=523
  _globals['_PBFTVIEWCHANGE']._serialized_start=525
  _globals['_PBFTVIEWCHANGE']._serialized_end=573
  _globals['_PBFTNEWVIEW']._serialized_start=575
  _globals['_PBFTNEWVIEW']._serialized_end=636
  _globals['_PBFTSIGNEDVOTE']._serialized_start=638
  _globals['_PBFTSIGNEDVOTE']._serialized_end=725
  _globals['_PBFTSEAL']._serialized_start=727
  _globals['_PBFTSEAL']._serialized_end=819
# @@protoc_insertion_point(module_scope)
