# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/processor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import transaction_pb2 as dgt__settings_dot_protobuf_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%dgt_settings/protobuf/processor.proto\x1a\'dgt_settings/protobuf/transaction.proto\"_\n\x11TpRegisterRequest\x12\x0e\n\x06\x66\x61mily\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nnamespaces\x18\x04 \x03(\t\x12\x15\n\rmax_occupancy\x18\x05 \x01(\r\"o\n\x12TpRegisterResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.TpRegisterResponse.Status\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"\x15\n\x13TpUnregisterRequest\"s\n\x14TpUnregisterResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.TpUnregisterResponse.Status\"-\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"n\n\x10TpProcessRequest\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.TransactionHeader\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x12\n\ncontext_id\x18\x04 \x01(\t\"\xb7\x01\n\x11TpProcessResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.TpProcessResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rextended_data\x18\x03 \x01(\x0c\"O\n\x06Status\x12\x10\n\x0cSTATUS_UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x17\n\x13INVALID_TRANSACTION\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x42(\n\x15sawtooth.sdk.protobufP\x01Z\rprocessor_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.processor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\rprocessor_pb2'
  _globals['_TPREGISTERREQUEST']._serialized_start=82
  _globals['_TPREGISTERREQUEST']._serialized_end=177
  _globals['_TPREGISTERRESPONSE']._serialized_start=179
  _globals['_TPREGISTERRESPONSE']._serialized_end=290
  _globals['_TPREGISTERRESPONSE_STATUS']._serialized_start=245
  _globals['_TPREGISTERRESPONSE_STATUS']._serialized_end=290
  _globals['_TPUNREGISTERREQUEST']._serialized_start=292
  _globals['_TPUNREGISTERREQUEST']._serialized_end=313
  _globals['_TPUNREGISTERRESPONSE']._serialized_start=315
  _globals['_TPUNREGISTERRESPONSE']._serialized_end=430
  _globals['_TPUNREGISTERRESPONSE_STATUS']._serialized_start=245
  _globals['_TPUNREGISTERRESPONSE_STATUS']._serialized_end=290
  _globals['_TPPROCESSREQUEST']._serialized_start=432
  _globals['_TPPROCESSREQUEST']._serialized_end=542
  _globals['_TPPROCESSRESPONSE']._serialized_start=545
  _globals['_TPPROCESSRESPONSE']._serialized_end=728
  _globals['_TPPROCESSRESPONSE_STATUS']._serialized_start=649
  _globals['_TPPROCESSRESPONSE_STATUS']._serialized_end=728
# @@protoc_insertion_point(module_scope)
