# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/settings.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$dgt_settings/protobuf/settings.proto\"\x89\x01\n\x0fSettingsPayload\x12\'\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x17.SettingsPayload.Action\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"?\n\x06\x41\x63tion\x12\x10\n\x0c\x41\x43TION_UNSET\x10\x00\x12\x0b\n\x07PROPOSE\x10\x01\x12\x08\n\x04VOTE\x10\x02\x12\x0c\n\x08TOPOLOGY\x10\x03\"@\n\x0fSettingProposal\x12\x0f\n\x07setting\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"s\n\x0bSettingVote\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x1f\n\x04vote\x18\x02 \x01(\x0e\x32\x11.SettingVote.Vote\".\n\x04Vote\x12\x0e\n\nVOTE_UNSET\x10\x00\x12\n\n\x06\x41\x43\x43\x45PT\x10\x01\x12\n\n\x06REJECT\x10\x02\"\xbb\x01\n\x10SettingCandidate\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\"\n\x08proposal\x18\x02 \x01(\x0b\x32\x10.SettingProposal\x12+\n\x05votes\x18\x03 \x03(\x0b\x32\x1c.SettingCandidate.VoteRecord\x1a\x41\n\nVoteRecord\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x1f\n\x04vote\x18\x02 \x01(\x0e\x32\x11.SettingVote.Vote\":\n\x11SettingCandidates\x12%\n\ncandidates\x18\x01 \x03(\x0b\x32\x11.SettingCandidate\"@\n\x0fSettingTopology\x12\x0f\n\x07setting\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\tB\x1e\n\x1asawtooth.settings.protobufP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032sawtooth.settings.protobufP\001'
  _globals['_SETTINGSPAYLOAD']._serialized_start=41
  _globals['_SETTINGSPAYLOAD']._serialized_end=178
  _globals['_SETTINGSPAYLOAD_ACTION']._serialized_start=115
  _globals['_SETTINGSPAYLOAD_ACTION']._serialized_end=178
  _globals['_SETTINGPROPOSAL']._serialized_start=180
  _globals['_SETTINGPROPOSAL']._serialized_end=244
  _globals['_SETTINGVOTE']._serialized_start=246
  _globals['_SETTINGVOTE']._serialized_end=361
  _globals['_SETTINGVOTE_VOTE']._serialized_start=315
  _globals['_SETTINGVOTE_VOTE']._serialized_end=361
  _globals['_SETTINGCANDIDATE']._serialized_start=364
  _globals['_SETTINGCANDIDATE']._serialized_end=551
  _globals['_SETTINGCANDIDATE_VOTERECORD']._serialized_start=486
  _globals['_SETTINGCANDIDATE_VOTERECORD']._serialized_end=551
  _globals['_SETTINGCANDIDATES']._serialized_start=553
  _globals['_SETTINGCANDIDATES']._serialized_end=611
  _globals['_SETTINGTOPOLOGY']._serialized_start=613
  _globals['_SETTINGTOPOLOGY']._serialized_end=677
# @@protoc_insertion_point(module_scope)
