# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgt_settings/protobuf/transaction_receipt.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dgt_settings.protobuf import events_pb2 as dgt__settings_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/dgt_settings/protobuf/transaction_receipt.proto\x1a\"dgt_settings/protobuf/events.proto\"\x8a\x01\n\x12TransactionReceipt\x12#\n\rstate_changes\x18\x01 \x03(\x0b\x32\x0c.StateChange\x12\x16\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x06.Event\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x0c\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\r\"{\n\x0bStateChange\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x1f\n\x04type\x18\x03 \x01(\x0e\x32\x11.StateChange.Type\"+\n\x04Type\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x07\n\x03SET\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\"6\n\x0fStateChangeList\x12#\n\rstate_changes\x18\x01 \x03(\x0b\x32\x0c.StateChangeB*\n\x15sawtooth.sdk.protobufP\x01Z\x0ftxn_receipt_pb2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgt_settings.protobuf.transaction_receipt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025sawtooth.sdk.protobufP\001Z\017txn_receipt_pb2'
  _globals['_TRANSACTIONRECEIPT']._serialized_start=88
  _globals['_TRANSACTIONRECEIPT']._serialized_end=226
  _globals['_STATECHANGE']._serialized_start=228
  _globals['_STATECHANGE']._serialized_end=351
  _globals['_STATECHANGE_TYPE']._serialized_start=308
  _globals['_STATECHANGE_TYPE']._serialized_end=351
  _globals['_STATECHANGELIST']._serialized_start=353
  _globals['_STATECHANGELIST']._serialized_end=407
# @@protoc_insertion_point(module_scope)
